A quick example of how the brisk solution calculates the group of ids who have the most points and a cost below or equal to the test_salary

In [1]:
import numpy as np

In [2]:
ids = np.array([np.arange(4), np.arange(4) + 4]).T #ids.shape == (4,2)
ids

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [3]:
ids2 = np.array([np.arange(5) + 8, np.arange(5) + 13]).T #ids2.shape == (5,2)
ids2

array([[ 8, 13],
       [ 9, 14],
       [10, 15],
       [11, 16],
       [12, 17]])

In [5]:
costs = np.array([5,7,8,9])
costs

array([5, 7, 8, 9])

In [6]:
costs2 = np.array([2,3,5,6,8])
costs2

array([2, 3, 5, 6, 8])

In [7]:
full_costs = costs[:,np.newaxis] + costs2
full_costs

array([[ 7,  8, 10, 11, 13],
       [ 9, 10, 12, 13, 15],
       [10, 11, 13, 14, 16],
       [11, 12, 14, 15, 17]])

In [8]:
points = np.array([3,5,6,4])
points

array([3, 5, 6, 4])

In [9]:
points2 = np.array([2,7,4,6,6])
points2

array([2, 7, 4, 6, 6])

In [10]:
full_points = points[:,np.newaxis] + points2[np.newaxis,:]
full_points

array([[ 5, 10,  7,  9,  9],
       [ 7, 12,  9, 11, 11],
       [ 8, 13, 10, 12, 12],
       [ 6, 11,  8, 10, 10]])

In [11]:
test_salary = 11
test_salary

11

In [12]:
valids = full_costs <= test_salary #groupings that are correct with the
valids

array([[ True,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True, False, False, False, False]])

In [13]:
possibilities = full_points * valids
possibilities

array([[ 5, 10,  7,  9,  0],
       [ 7, 12,  0,  0,  0],
       [ 8, 13,  0,  0,  0],
       [ 6,  0,  0,  0,  0]])

In [15]:
x, y = np.unravel_index(possibilities.argmax(), possibilities.shape)
x, y #x #refers to index of ids, y refers to index of ids2

(2, 1)

In [16]:
best_inds = np.concatenate([ids[x], ids2[y]])
best_inds

array([ 2,  6,  9, 14])

In [20]:
full_points[x][y]

13

In [21]:
full_costs[x][y]

11